### ISSUE TITLE
Moved to the repo

### ISSUE THREAD

**Issue by demmm** [KaOS-Community-Packages/RSS-Guard#1]
2.5.0 is up in the build repo, once moved to apps, rssguard will be removed from KCP

**Comment by timcowchip** [comment]
would you like me to continue to maintain the package? 

On Sunday, July 19, 2015 12:35:10 PM demmm wrote:


2.5.0 is up in the build repo, once moved to apps, rssguard will be removed from KCP 
—Reply to this email directly or view it on GitHub[1].[2]




--------
[1] https://github.com/KaOS-Community-Packages/RSS-Guard/issues/1
[2] https://github.com/notifications/beacon/AHwwy3XoUUTat1pgFyK3NN-exiwK6PPNks5oe_NugaJpZM4FbkmU.gif

**Comment by demmm** [comment]
If you could flag it as outdated when you see a new release, that would be great.
It is moved now, so closing this issue and removing from KCP.
